sudo: true
language: bash

matrix:
    include:
        - os: linux
        - os: osx

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install bats; brew link --force bats; fi

script: make all

after_success: make notify result=success

after_failure: make notify result=failure
